---
name: YamlValidations
on:
  push:
    branches:
      - '**'
      - master
  pull_request:
    branches:
      - '**'
      - master
jobs:
  YamlValidations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting all Yaml Files
        uses: frenck/action-yamllint@v1